# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d3fa46486613894daec5fcd4aa6a3806"
application_url = "https://daraz-app-seven.vercel.app"
embedded = true
name = "daraz"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_inventory,read_publications,write_publications"
optional_scopes = [ ]
use_legacy_install_flow = false

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/create"
  topics = [ "products/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/update"
  topics = [ "products/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/inventory_levels/update"
  topics = [ "inventory_levels/update" ]

[auth]
redirect_urls = [ "https://daraz-app-seven.vercel.app/auth/callback" ]
